 - name: Declare a variable at play level  #Its a play level
   hosts: all
   connection: local
   vars:  #to declare a variable
     URL : play.example.com  #URL is a variable
   tasks:
     - name:  Access a variable
       ansible.builtin.debug:
         msg: URL == {{URL}}  #accessing a variable #and all the tasks can be accessible this variable.

 - name: Declare a variable in another file
   hosts: all
   connection: local
   vars_files:
     - varfile.yml #file
   tasks:
     - name: Access a variable
       ansible.builtin.debug:
         msg: URL == {{URL}}

##var_files can also be declared on task level.

 - name: Declare a variable at task level  #Its a task level
   hosts: all
   connection: local
   tasks:
     - name: Declare and Access a variable
       ansible.builtin.debug:
         msg: URL == {{URL}}
       vars: #to declare a variable
         URL: task.example.com

 - name: Declare a variable from inventory file
   hosts: all
   connection: local
   tasks:
     - name: Access variable
       ansible.builtin.debug:
         msg: URL == {{URL}}

