 - name: Declare a variable at play level
   hosts: all
   conection: local
   vars: #to declare a variable
     URL : play.example.com #URL is a variable
   tasks:
     - name:  Access a variable
       ansible.builtin.debug:
         msg: URL == ((URL}} #accessing a variable
